<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
	<PublishSingleFile>true</PublishSingleFile>
	<SelfContained>true</SelfContained>
	<IncludeAllContentForSelfExtract>true</IncludeAllContentForSelfExtract>
	<IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows7.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\HaloStats.Domain\HaloStats.Domain.csproj" />
  </ItemGroup>

</Project>
