<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
	<PublishSingleFile>true</PublishSingleFile>
	<SelfContained>true</SelfContained>
	<IncludeAllContentForSelfExtract>true</IncludeAllContentForSelfExtract>
	<IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows7.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <ApplicationIcon>Resources\halo.ico</ApplicationIcon>
  </PropertyGroup>
  <ItemGroup>
    <Content Include="Resources\halo.ico" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\HaloStats.Web.Shared\HaloStats.Web.Shared.csproj" />
  </ItemGroup>

</Project>
