// <auto-generated />
using System;
using HaloStats.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HaloStats.Database.Migrations
{
    [DbContext(typeof(HaloStatsDbContext))]
    [Migration("20251002140234_AddTeamSizeToGamesTable")]
    partial class AddTeamSizeToGamesTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("HaloStats.Database.Entities.Game", b =>
                {
                    b.Property<Guid>("GameId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeletedByIp")
                        .HasColumnType("text");

                    b.Property<byte>("GameEnum")
                        .HasColumnType("smallint");

                    b.Property<string>("GameTypeName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("GameUniqueId")
                        .HasColumnType("uuid");

                    b.Property<bool>("HasNetworkMembersInParty")
                        .HasColumnType("boolean");

                    b.Property<long>("HopperId")
                        .HasColumnType("bigint");

                    b.Property<string>("HopperName")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDuplicateGame")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsMatchmaking")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsTeamsEnabled")
                        .HasColumnType("boolean");

                    b.Property<bool>("LastMatchIncomplete")
                        .HasColumnType("boolean");

                    b.Property<int>("PartySize")
                        .HasColumnType("integer");

                    b.Property<DateTime>("ReportedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("WhosReportingIp")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("GameId");

                    b.HasIndex("GameUniqueId");

                    b.HasIndex("ReportedAt");

                    b.ToTable("Games");
                });

            modelBuilder.Entity("HaloStats.Database.Entities.GamePlayer", b =>
                {
                    b.Property<Guid>("GamePlayerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Assists")
                        .HasColumnType("integer");

                    b.Property<int>("Avatar")
                        .HasColumnType("integer");

                    b.Property<int>("Betrayals")
                        .HasColumnType("integer");

                    b.Property<string>("ClanTag")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("CompletedGame")
                        .HasColumnType("integer");

                    b.Property<int>("Deaths")
                        .HasColumnType("integer");

                    b.Property<int>("EmblemColor0")
                        .HasColumnType("integer");

                    b.Property<int>("EmblemColor1")
                        .HasColumnType("integer");

                    b.Property<int>("EmblemTexture0")
                        .HasColumnType("integer");

                    b.Property<int>("EmblemTexture1")
                        .HasColumnType("integer");

                    b.Property<Guid>("GameId")
                        .HasColumnType("uuid");

                    b.Property<int>("GameMode")
                        .HasColumnType("integer");

                    b.Property<string>("Gamertag")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsGuest")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsWinner")
                        .HasColumnType("boolean");

                    b.Property<int>("KilledMostPlayerCount")
                        .HasColumnType("integer");

                    b.Property<int>("KilledMostPlayerIndex")
                        .HasColumnType("integer");

                    b.Property<int>("Kills")
                        .HasColumnType("integer");

                    b.Property<int>("KillsGrenade")
                        .HasColumnType("integer");

                    b.Property<int>("KillsMelee")
                        .HasColumnType("integer");

                    b.Property<int>("KillsOther")
                        .HasColumnType("integer");

                    b.Property<int>("KillsWeapon")
                        .HasColumnType("integer");

                    b.Property<int>("MostKilledByPlayerCount")
                        .HasColumnType("integer");

                    b.Property<int>("MostKilledByPlayerIndex")
                        .HasColumnType("integer");

                    b.Property<int>("MostKillsInARow")
                        .HasColumnType("integer");

                    b.Property<int>("MostUsedWeapon")
                        .HasColumnType("integer");

                    b.Property<int>("MostUsedWeaponCount")
                        .HasColumnType("integer");

                    b.Property<int>("Nameplate")
                        .HasColumnType("integer");

                    b.Property<int>("Place")
                        .HasColumnType("integer");

                    b.Property<int>("Score")
                        .HasColumnType("integer");

                    b.Property<int>("SecondsAlive")
                        .HasColumnType("integer");

                    b.Property<int>("SecondsPlayed")
                        .HasColumnType("integer");

                    b.Property<string>("ServiceId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Standing")
                        .HasColumnType("integer");

                    b.Property<int>("Suicides")
                        .HasColumnType("integer");

                    b.Property<int>("TeamId")
                        .HasColumnType("integer");

                    b.Property<int>("TotalMedalCount")
                        .HasColumnType("integer");

                    b.Property<string>("XboxUserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("GamePlayerId");

                    b.HasIndex("GameId");

                    b.HasIndex("Gamertag");

                    b.ToTable("GamePlayers");
                });

            modelBuilder.Entity("HaloStats.Database.Entities.GamePlayerCustomStat", b =>
                {
                    b.Property<Guid>("GamePlayerCustomStatId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("GamePlayerId")
                        .HasColumnType("uuid");

                    b.Property<string>("StatName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("GamePlayerCustomStatId");

                    b.HasIndex("GamePlayerId");

                    b.ToTable("GamePlayerCustomStats");
                });

            modelBuilder.Entity("HaloStats.Database.Entities.GamePlayerMedal", b =>
                {
                    b.Property<Guid>("GamePlayerMedalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Count")
                        .HasColumnType("integer");

                    b.Property<Guid>("GamePlayerId")
                        .HasColumnType("uuid");

                    b.Property<int>("MedalId")
                        .HasColumnType("integer");

                    b.HasKey("GamePlayerMedalId");

                    b.HasIndex("GamePlayerId");

                    b.ToTable("GamePlayerMedals");
                });

            modelBuilder.Entity("HaloStats.Database.Entities.Gamertag", b =>
                {
                    b.Property<Guid>("GamertagId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("XboxUserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("GamertagId");

                    b.HasIndex("Name");

                    b.ToTable("Gamertags");
                });

            modelBuilder.Entity("HaloStats.Database.Entities.StoredProcs.Usp_GetTopOpponentPairs", b =>
                {
                    b.Property<int>("GamesPlayedAgainst")
                        .HasColumnType("integer");

                    b.Property<int>("LossesAgainst")
                        .HasColumnType("integer");

                    b.Property<string>("OpponentGamertag")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("WinRate")
                        .HasColumnType("numeric");

                    b.Property<int>("WinsAgainst")
                        .HasColumnType("integer");

                    b.ToTable((string)null);

                    b.ToView(null, (string)null);
                });

            modelBuilder.Entity("HaloStats.Database.Entities.StoredProcs.Usp_GetTopTeammatePairs", b =>
                {
                    b.Property<int>("GamesPlayedTogether")
                        .HasColumnType("integer");

                    b.Property<int>("LossesTogether")
                        .HasColumnType("integer");

                    b.Property<string>("PlayerOneGamertag")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PlayerTwoGamertag")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("WinRate")
                        .HasColumnType("numeric");

                    b.Property<int>("WinsTogether")
                        .HasColumnType("integer");

                    b.ToTable((string)null);

                    b.ToView(null, (string)null);
                });

            modelBuilder.Entity("HaloStats.Database.Entities.StoredProcs.Usp_SearchTopPlayers", b =>
                {
                    b.Property<int>("Deaths")
                        .HasColumnType("integer");

                    b.Property<string>("Gamertag")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("KillDeathRatio")
                        .HasColumnType("numeric");

                    b.Property<int>("Kills")
                        .HasColumnType("integer");

                    b.Property<int>("Rank")
                        .HasColumnType("integer");

                    b.Property<int>("TotalCount")
                        .HasColumnType("integer");

                    b.ToTable((string)null);

                    b.ToView(null, (string)null);
                });

            modelBuilder.Entity("HaloStats.Database.Entities.GamePlayer", b =>
                {
                    b.HasOne("HaloStats.Database.Entities.Game", null)
                        .WithMany("Players")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HaloStats.Database.Entities.GamePlayerCustomStat", b =>
                {
                    b.HasOne("HaloStats.Database.Entities.GamePlayer", null)
                        .WithMany("CustomStats")
                        .HasForeignKey("GamePlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HaloStats.Database.Entities.GamePlayerMedal", b =>
                {
                    b.HasOne("HaloStats.Database.Entities.GamePlayer", null)
                        .WithMany("Medals")
                        .HasForeignKey("GamePlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HaloStats.Database.Entities.Game", b =>
                {
                    b.Navigation("Players");
                });

            modelBuilder.Entity("HaloStats.Database.Entities.GamePlayer", b =>
                {
                    b.Navigation("CustomStats");

                    b.Navigation("Medals");
                });
#pragma warning restore 612, 618
        }
    }
}
